import type { CarcasseForResponseForRegistry, CarcasseGetForRegistry } from '~/types/carcasse';
import updateCarcasseStatus from './get-carcasse-status';
import dayjs from 'dayjs';

export function mapCarcasseForRegistry(carcasse: CarcasseGetForRegistry): CarcasseForResponseForRegistry {
  const fei = carcasse.Fei;
  return {
    zacharie_carcasse_id: carcasse.zacharie_carcasse_id,
    numero_bracelet: carcasse.numero_bracelet,
    fei_numero: carcasse.fei_numero,
    date_mise_a_mort: carcasse.date_mise_a_mort,
    type: carcasse.type,
    nombre_d_animaux: carcasse.nombre_d_animaux,
    heure_mise_a_mort: carcasse.heure_mise_a_mort,
    heure_evisceration: carcasse.heure_evisceration,
    espece: carcasse.espece,
    intermediaire_carcasse_refus_intermediaire_id: carcasse.intermediaire_carcasse_refus_intermediaire_id,
    intermediaire_carcasse_refus_motif: carcasse.intermediaire_carcasse_refus_motif,
    premier_detenteur_depot_entity_name_cache: carcasse.premier_detenteur_depot_entity_name_cache,
    latest_intermediaire_signed_at: carcasse.latest_intermediaire_signed_at,
    intermediaire_carcasse_manquante: carcasse.intermediaire_carcasse_manquante,
    svi_carcasse_commentaire: carcasse.svi_carcasse_commentaire,
    svi_ipm1_date: carcasse.svi_ipm1_date,
    svi_ipm1_presentee_inspection: carcasse.svi_ipm1_presentee_inspection,
    svi_ipm1_user_id: carcasse.svi_ipm1_user_id,
    svi_ipm1_user_name_cache: carcasse.svi_ipm1_user_name_cache,
    svi_ipm1_protocole: carcasse.svi_ipm1_protocole,
    svi_ipm1_pieces: carcasse.svi_ipm1_pieces,
    svi_ipm1_lesions_ou_motifs: carcasse.svi_ipm1_lesions_ou_motifs,
    svi_ipm1_nombre_animaux: carcasse.svi_ipm1_nombre_animaux,
    svi_ipm1_commentaire: carcasse.svi_ipm1_commentaire,
    svi_ipm1_decision: carcasse.svi_ipm1_decision,
    svi_ipm1_duree_consigne: carcasse.svi_ipm1_duree_consigne,
    svi_ipm1_poids_consigne: carcasse.svi_ipm1_poids_consigne,
    svi_ipm1_signed_at: carcasse.svi_ipm1_signed_at,
    svi_ipm2_date: carcasse.svi_ipm2_date,
    svi_ipm2_presentee_inspection: carcasse.svi_ipm2_presentee_inspection,
    svi_ipm2_user_id: carcasse.svi_ipm2_user_id,
    svi_ipm2_user_name_cache: carcasse.svi_ipm2_user_name_cache,
    svi_ipm2_protocole: carcasse.svi_ipm2_protocole,
    svi_ipm2_pieces: carcasse.svi_ipm2_pieces,
    svi_ipm2_lesions_ou_motifs: carcasse.svi_ipm2_lesions_ou_motifs,
    svi_ipm2_nombre_animaux: carcasse.svi_ipm2_nombre_animaux,
    svi_ipm2_commentaire: carcasse.svi_ipm2_commentaire,
    svi_ipm2_decision: carcasse.svi_ipm2_decision,
    svi_ipm2_traitement_assainissant: carcasse.svi_ipm2_traitement_assainissant,
    svi_ipm2_traitement_assainissant_cuisson_temps: carcasse.svi_ipm2_traitement_assainissant_cuisson_temps,
    svi_ipm2_traitement_assainissant_cuisson_temp: carcasse.svi_ipm2_traitement_assainissant_cuisson_temp,
    svi_ipm2_traitement_assainissant_congelation_temps:
      carcasse.svi_ipm2_traitement_assainissant_congelation_temps,
    svi_ipm2_traitement_assainissant_congelation_temp:
      carcasse.svi_ipm2_traitement_assainissant_congelation_temp,
    svi_ipm2_traitement_assainissant_type: carcasse.svi_ipm2_traitement_assainissant_type,
    svi_ipm2_traitement_assainissant_paramètres: carcasse.svi_ipm2_traitement_assainissant_paramètres,
    svi_ipm2_traitement_assainissant_etablissement: carcasse.svi_ipm2_traitement_assainissant_etablissement,
    svi_ipm2_traitement_assainissant_poids: carcasse.svi_ipm2_traitement_assainissant_poids,
    svi_ipm2_poids_saisie: carcasse.svi_ipm2_poids_saisie,
    svi_ipm2_signed_at: carcasse.svi_ipm2_signed_at,
    created_at: carcasse.created_at,
    updated_at: carcasse.updated_at,
    deleted_at: carcasse.deleted_at,
    is_synced: carcasse.is_synced,
    svi_carcasse_status: carcasse.svi_carcasse_status || updateCarcasseStatus(carcasse),
    svi_carcasse_status_set_at:
      carcasse.svi_carcasse_status_set_at || fei.automatic_closed_at || fei.svi_closed_at,
    svi_assigned_to_fei_at: carcasse.svi_assigned_to_fei_at || fei.svi_assigned_at,
    svi_carcasse_archived: !!fei.automatic_closed_at || dayjs().diff(fei.svi_assigned_at, 'day') > 10,
    fei_date_mise_a_mort: fei.date_mise_a_mort,
    fei_commune_mise_a_mort: fei.commune_mise_a_mort,
    fei_heure_mise_a_mort_premiere_carcasse: fei.heure_mise_a_mort_premiere_carcasse,
    fei_heure_evisceration_derniere_carcasse: fei.heure_evisceration_derniere_carcasse,
    fei_examinateur_initial_date_approbation_mise_sur_le_marche:
      fei.examinateur_initial_date_approbation_mise_sur_le_marche,
    fei_premier_detenteur_name_cache: fei.premier_detenteur_name_cache,
    fei_premier_detenteur_depot_ccg_at: fei.premier_detenteur_depot_ccg_at,
    fei_premier_detenteur_depot_entity_name_cache: fei.premier_detenteur_depot_entity_name_cache,
    fei_svi_assigned_at: fei.svi_assigned_at,
    fei_svi_entity_id: fei.svi_entity_id,
    fei_svi_user_id: fei.svi_user_id,
    fei_svi_closed_at: fei.svi_closed_at,
    latest_intermediaire_name_cache: fei.latest_intermediaire_name_cache,
    fei_created_at: fei.created_at,
    fei_updated_at: fei.updated_at,
    fei_deleted_at: fei.deleted_at,
    fei_automatic_closed_at: fei.automatic_closed_at,
  };
}
