-- AlterEnum
ALTER TYPE "EntityTypes" ADD VALUE 'FDC';
ALTER TYPE "EntityTypes" ADD VALUE 'FRC';
ALTER TYPE "EntityTypes" ADD VALUE 'FNC';

-- Les anciens comptes FDC / FRC / FNC sont supprimés : les fédérations sont désormais des entités
DELETE FROM "User" WHERE "roles" && ARRAY['FDC', 'FRC', 'FNC']::"UserRoles"[] OR "role" IN ('FDC', 'FRC', 'FNC');

-- AlterEnum
BEGIN;
CREATE TYPE "UserRoles_new" AS ENUM ('ADMIN', 'CHASSEUR', 'COLLECTEUR_PRO', 'ETG', 'SVI', 'COMMERCE_DE_DETAIL', 'CANTINE_OU_RESTAURATION_COLLECTIVE', 'ASSOCIATION_CARITATIVE', 'REPAS_DE_CHASSE_OU_ASSOCIATIF', 'CONSOMMATEUR_FINAL', 'LABORATOIRE', 'FEDERATION');
ALTER TABLE "User" ALTER COLUMN "roles" TYPE "UserRoles_new"[] USING ("roles"::text::"UserRoles_new"[]);
ALTER TABLE "User" ALTER COLUMN "role" TYPE "UserRoles_new" USING ("role"::text::"UserRoles_new");
ALTER TYPE "UserRoles" RENAME TO "UserRoles_old";
ALTER TYPE "UserRoles_new" RENAME TO "UserRoles";
DROP TYPE "UserRoles_old";
COMMIT;

-- AlterTable
ALTER TABLE "Entity" ADD COLUMN     "scope_departements_codes" TEXT[];

-- AlterTable
ALTER TABLE "User" DROP COLUMN "scope_departements_codes";

-- Pré-création des fédérations : une FDC par département, une FRC par région, la FNC
INSERT INTO "Entity" ("id", "type", "raison_sociale", "nom_d_usage", "scope_departements_codes") VALUES
('federation-fnc', 'FNC', 'Fédération Nationale des Chasseurs', 'FNC', ARRAY['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '21', '22', '23', '24', '25', '26', '27', '28', '29', '2A', '2B', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '971', '972', '973', '974', '975', '976', '977', '978', '984', '986', '987', '988']::TEXT[]),
('federation-frc-ARA', 'FRC', 'Fédération Régionale des Chasseurs – Auvergne-Rhône-Alpes', 'FRC Auvergne-Rhône-Alpes', ARRAY['01', '03', '07', '15', '26', '38', '42', '43', '63', '69', '73', '74']::TEXT[]),
('federation-frc-BFC', 'FRC', 'Fédération Régionale des Chasseurs – Bourgogne-Franche-Comté', 'FRC Bourgogne-Franche-Comté', ARRAY['21', '25', '39', '58', '70', '71', '89', '90']::TEXT[]),
('federation-frc-BRE', 'FRC', 'Fédération Régionale des Chasseurs – Bretagne', 'FRC Bretagne', ARRAY['22', '29', '35', '56']::TEXT[]),
('federation-frc-CVL', 'FRC', 'Fédération Régionale des Chasseurs – Centre-Val de Loire', 'FRC Centre-Val de Loire', ARRAY['18', '28', '36', '37', '41', '45']::TEXT[]),
('federation-frc-COR', 'FRC', 'Fédération Régionale des Chasseurs – Corse', 'FRC Corse', ARRAY['2A', '2B']::TEXT[]),
('federation-frc-GES', 'FRC', 'Fédération Régionale des Chasseurs – Grand Est', 'FRC Grand Est', ARRAY['08', '10', '51', '52', '54', '55', '57', '67', '68', '88']::TEXT[]),
('federation-frc-HDF', 'FRC', 'Fédération Régionale des Chasseurs – Hauts-de-France', 'FRC Hauts-de-France', ARRAY['02', '59', '60', '62', '80']::TEXT[]),
('federation-frc-IDF', 'FRC', 'Fédération Régionale des Chasseurs – Île-de-France', 'FRC Île-de-France', ARRAY['75', '77', '78', '91', '92', '93', '94', '95']::TEXT[]),
('federation-frc-NOR', 'FRC', 'Fédération Régionale des Chasseurs – Normandie', 'FRC Normandie', ARRAY['14', '27', '50', '61', '76']::TEXT[]),
('federation-frc-NAQ', 'FRC', 'Fédération Régionale des Chasseurs – Nouvelle-Aquitaine', 'FRC Nouvelle-Aquitaine', ARRAY['16', '17', '19', '23', '24', '33', '40', '47', '64', '79', '86', '87']::TEXT[]),
('federation-frc-OCC', 'FRC', 'Fédération Régionale des Chasseurs – Occitanie', 'FRC Occitanie', ARRAY['09', '11', '12', '30', '31', '32', '34', '46', '48', '65', '66', '81', '82']::TEXT[]),
('federation-frc-PDL', 'FRC', 'Fédération Régionale des Chasseurs – Pays de la Loire', 'FRC Pays de la Loire', ARRAY['44', '49', '53', '72', '85']::TEXT[]),
('federation-frc-PAC', 'FRC', 'Fédération Régionale des Chasseurs – Provence-Alpes-Côte d''Azur', 'FRC Provence-Alpes-Côte d''Azur', ARRAY['04', '05', '06', '13', '83', '84']::TEXT[]),
('federation-frc-GLP', 'FRC', 'Fédération Régionale des Chasseurs – Guadeloupe', 'FRC Guadeloupe', ARRAY['971']::TEXT[]),
('federation-frc-MTQ', 'FRC', 'Fédération Régionale des Chasseurs – Martinique', 'FRC Martinique', ARRAY['972']::TEXT[]),
('federation-frc-GUF', 'FRC', 'Fédération Régionale des Chasseurs – Guyane', 'FRC Guyane', ARRAY['973']::TEXT[]),
('federation-frc-REU', 'FRC', 'Fédération Régionale des Chasseurs – La Réunion', 'FRC La Réunion', ARRAY['974']::TEXT[]),
('federation-frc-SPM', 'FRC', 'Fédération Régionale des Chasseurs – Saint-Pierre-et-Miquelon', 'FRC Saint-Pierre-et-Miquelon', ARRAY['975']::TEXT[]),
('federation-frc-MYT', 'FRC', 'Fédération Régionale des Chasseurs – Mayotte', 'FRC Mayotte', ARRAY['976']::TEXT[]),
('federation-frc-BLM', 'FRC', 'Fédération Régionale des Chasseurs – Saint-Barthélemy', 'FRC Saint-Barthélemy', ARRAY['977']::TEXT[]),
('federation-frc-MAF', 'FRC', 'Fédération Régionale des Chasseurs – Saint-Martin', 'FRC Saint-Martin', ARRAY['978']::TEXT[]),
('federation-frc-ATF', 'FRC', 'Fédération Régionale des Chasseurs – Terres australes et antarctiques françaises', 'FRC Terres australes et antarctiques françaises', ARRAY['984']::TEXT[]),
('federation-frc-WLF', 'FRC', 'Fédération Régionale des Chasseurs – Wallis-et-Futuna', 'FRC Wallis-et-Futuna', ARRAY['986']::TEXT[]),
('federation-frc-PYF', 'FRC', 'Fédération Régionale des Chasseurs – Polynésie française', 'FRC Polynésie française', ARRAY['987']::TEXT[]),
('federation-frc-NCL', 'FRC', 'Fédération Régionale des Chasseurs – Nouvelle-Calédonie', 'FRC Nouvelle-Calédonie', ARRAY['988']::TEXT[]),
('federation-fdc-01', 'FDC', 'Fédération Départementale des Chasseurs – Ain', 'FDC Ain (01)', ARRAY['01']::TEXT[]),
('federation-fdc-02', 'FDC', 'Fédération Départementale des Chasseurs – Aisne', 'FDC Aisne (02)', ARRAY['02']::TEXT[]),
('federation-fdc-03', 'FDC', 'Fédération Départementale des Chasseurs – Allier', 'FDC Allier (03)', ARRAY['03']::TEXT[]),
('federation-fdc-04', 'FDC', 'Fédération Départementale des Chasseurs – Alpes-de-Haute-Provence', 'FDC Alpes-de-Haute-Provence (04)', ARRAY['04']::TEXT[]),
('federation-fdc-05', 'FDC', 'Fédération Départementale des Chasseurs – Hautes-Alpes', 'FDC Hautes-Alpes (05)', ARRAY['05']::TEXT[]),
('federation-fdc-06', 'FDC', 'Fédération Départementale des Chasseurs – Alpes-Maritimes', 'FDC Alpes-Maritimes (06)', ARRAY['06']::TEXT[]),
('federation-fdc-07', 'FDC', 'Fédération Départementale des Chasseurs – Ardèche', 'FDC Ardèche (07)', ARRAY['07']::TEXT[]),
('federation-fdc-08', 'FDC', 'Fédération Départementale des Chasseurs – Ardennes', 'FDC Ardennes (08)', ARRAY['08']::TEXT[]),
('federation-fdc-09', 'FDC', 'Fédération Départementale des Chasseurs – Ariège', 'FDC Ariège (09)', ARRAY['09']::TEXT[]),
('federation-fdc-10', 'FDC', 'Fédération Départementale des Chasseurs – Aube', 'FDC Aube (10)', ARRAY['10']::TEXT[]),
('federation-fdc-11', 'FDC', 'Fédération Départementale des Chasseurs – Aude', 'FDC Aude (11)', ARRAY['11']::TEXT[]),
('federation-fdc-12', 'FDC', 'Fédération Départementale des Chasseurs – Aveyron', 'FDC Aveyron (12)', ARRAY['12']::TEXT[]),
('federation-fdc-13', 'FDC', 'Fédération Départementale des Chasseurs – Bouches-du-Rhône', 'FDC Bouches-du-Rhône (13)', ARRAY['13']::TEXT[]),
('federation-fdc-14', 'FDC', 'Fédération Départementale des Chasseurs – Calvados', 'FDC Calvados (14)', ARRAY['14']::TEXT[]),
('federation-fdc-15', 'FDC', 'Fédération Départementale des Chasseurs – Cantal', 'FDC Cantal (15)', ARRAY['15']::TEXT[]),
('federation-fdc-16', 'FDC', 'Fédération Départementale des Chasseurs – Charente', 'FDC Charente (16)', ARRAY['16']::TEXT[]),
('federation-fdc-17', 'FDC', 'Fédération Départementale des Chasseurs – Charente-Maritime', 'FDC Charente-Maritime (17)', ARRAY['17']::TEXT[]),
('federation-fdc-18', 'FDC', 'Fédération Départementale des Chasseurs – Cher', 'FDC Cher (18)', ARRAY['18']::TEXT[]),
('federation-fdc-19', 'FDC', 'Fédération Départementale des Chasseurs – Corrèze', 'FDC Corrèze (19)', ARRAY['19']::TEXT[]),
('federation-fdc-21', 'FDC', 'Fédération Départementale des Chasseurs – Côte-d''Or', 'FDC Côte-d''Or (21)', ARRAY['21']::TEXT[]),
('federation-fdc-22', 'FDC', 'Fédération Départementale des Chasseurs – Côtes-d''Armor', 'FDC Côtes-d''Armor (22)', ARRAY['22']::TEXT[]),
('federation-fdc-23', 'FDC', 'Fédération Départementale des Chasseurs – Creuse', 'FDC Creuse (23)', ARRAY['23']::TEXT[]),
('federation-fdc-24', 'FDC', 'Fédération Départementale des Chasseurs – Dordogne', 'FDC Dordogne (24)', ARRAY['24']::TEXT[]),
('federation-fdc-25', 'FDC', 'Fédération Départementale des Chasseurs – Doubs', 'FDC Doubs (25)', ARRAY['25']::TEXT[]),
('federation-fdc-26', 'FDC', 'Fédération Départementale des Chasseurs – Drôme', 'FDC Drôme (26)', ARRAY['26']::TEXT[]),
('federation-fdc-27', 'FDC', 'Fédération Départementale des Chasseurs – Eure', 'FDC Eure (27)', ARRAY['27']::TEXT[]),
('federation-fdc-28', 'FDC', 'Fédération Départementale des Chasseurs – Eure-et-Loir', 'FDC Eure-et-Loir (28)', ARRAY['28']::TEXT[]),
('federation-fdc-29', 'FDC', 'Fédération Départementale des Chasseurs – Finistère', 'FDC Finistère (29)', ARRAY['29']::TEXT[]),
('federation-fdc-2A', 'FDC', 'Fédération Départementale des Chasseurs – Corse-du-Sud', 'FDC Corse-du-Sud (2A)', ARRAY['2A']::TEXT[]),
('federation-fdc-2B', 'FDC', 'Fédération Départementale des Chasseurs – Haute-Corse', 'FDC Haute-Corse (2B)', ARRAY['2B']::TEXT[]),
('federation-fdc-30', 'FDC', 'Fédération Départementale des Chasseurs – Gard', 'FDC Gard (30)', ARRAY['30']::TEXT[]),
('federation-fdc-31', 'FDC', 'Fédération Départementale des Chasseurs – Haute-Garonne', 'FDC Haute-Garonne (31)', ARRAY['31']::TEXT[]),
('federation-fdc-32', 'FDC', 'Fédération Départementale des Chasseurs – Gers', 'FDC Gers (32)', ARRAY['32']::TEXT[]),
('federation-fdc-33', 'FDC', 'Fédération Départementale des Chasseurs – Gironde', 'FDC Gironde (33)', ARRAY['33']::TEXT[]),
('federation-fdc-34', 'FDC', 'Fédération Départementale des Chasseurs – Hérault', 'FDC Hérault (34)', ARRAY['34']::TEXT[]),
('federation-fdc-35', 'FDC', 'Fédération Départementale des Chasseurs – Ille-et-Vilaine', 'FDC Ille-et-Vilaine (35)', ARRAY['35']::TEXT[]),
('federation-fdc-36', 'FDC', 'Fédération Départementale des Chasseurs – Indre', 'FDC Indre (36)', ARRAY['36']::TEXT[]),
('federation-fdc-37', 'FDC', 'Fédération Départementale des Chasseurs – Indre-et-Loire', 'FDC Indre-et-Loire (37)', ARRAY['37']::TEXT[]),
('federation-fdc-38', 'FDC', 'Fédération Départementale des Chasseurs – Isère', 'FDC Isère (38)', ARRAY['38']::TEXT[]),
('federation-fdc-39', 'FDC', 'Fédération Départementale des Chasseurs – Jura', 'FDC Jura (39)', ARRAY['39']::TEXT[]),
('federation-fdc-40', 'FDC', 'Fédération Départementale des Chasseurs – Landes', 'FDC Landes (40)', ARRAY['40']::TEXT[]),
('federation-fdc-41', 'FDC', 'Fédération Départementale des Chasseurs – Loir-et-Cher', 'FDC Loir-et-Cher (41)', ARRAY['41']::TEXT[]),
('federation-fdc-42', 'FDC', 'Fédération Départementale des Chasseurs – Loire', 'FDC Loire (42)', ARRAY['42']::TEXT[]),
('federation-fdc-43', 'FDC', 'Fédération Départementale des Chasseurs – Haute-Loire', 'FDC Haute-Loire (43)', ARRAY['43']::TEXT[]),
('federation-fdc-44', 'FDC', 'Fédération Départementale des Chasseurs – Loire-Atlantique', 'FDC Loire-Atlantique (44)', ARRAY['44']::TEXT[]),
('federation-fdc-45', 'FDC', 'Fédération Départementale des Chasseurs – Loiret', 'FDC Loiret (45)', ARRAY['45']::TEXT[]),
('federation-fdc-46', 'FDC', 'Fédération Départementale des Chasseurs – Lot', 'FDC Lot (46)', ARRAY['46']::TEXT[]),
('federation-fdc-47', 'FDC', 'Fédération Départementale des Chasseurs – Lot-et-Garonne', 'FDC Lot-et-Garonne (47)', ARRAY['47']::TEXT[]),
('federation-fdc-48', 'FDC', 'Fédération Départementale des Chasseurs – Lozère', 'FDC Lozère (48)', ARRAY['48']::TEXT[]),
('federation-fdc-49', 'FDC', 'Fédération Départementale des Chasseurs – Maine-et-Loire', 'FDC Maine-et-Loire (49)', ARRAY['49']::TEXT[]),
('federation-fdc-50', 'FDC', 'Fédération Départementale des Chasseurs – Manche', 'FDC Manche (50)', ARRAY['50']::TEXT[]),
('federation-fdc-51', 'FDC', 'Fédération Départementale des Chasseurs – Marne', 'FDC Marne (51)', ARRAY['51']::TEXT[]),
('federation-fdc-52', 'FDC', 'Fédération Départementale des Chasseurs – Haute-Marne', 'FDC Haute-Marne (52)', ARRAY['52']::TEXT[]),
('federation-fdc-53', 'FDC', 'Fédération Départementale des Chasseurs – Mayenne', 'FDC Mayenne (53)', ARRAY['53']::TEXT[]),
('federation-fdc-54', 'FDC', 'Fédération Départementale des Chasseurs – Meurthe-et-Moselle', 'FDC Meurthe-et-Moselle (54)', ARRAY['54']::TEXT[]),
('federation-fdc-55', 'FDC', 'Fédération Départementale des Chasseurs – Meuse', 'FDC Meuse (55)', ARRAY['55']::TEXT[]),
('federation-fdc-56', 'FDC', 'Fédération Départementale des Chasseurs – Morbihan', 'FDC Morbihan (56)', ARRAY['56']::TEXT[]),
('federation-fdc-57', 'FDC', 'Fédération Départementale des Chasseurs – Moselle', 'FDC Moselle (57)', ARRAY['57']::TEXT[]),
('federation-fdc-58', 'FDC', 'Fédération Départementale des Chasseurs – Nièvre', 'FDC Nièvre (58)', ARRAY['58']::TEXT[]),
('federation-fdc-59', 'FDC', 'Fédération Départementale des Chasseurs – Nord', 'FDC Nord (59)', ARRAY['59']::TEXT[]),
('federation-fdc-60', 'FDC', 'Fédération Départementale des Chasseurs – Oise', 'FDC Oise (60)', ARRAY['60']::TEXT[]),
('federation-fdc-61', 'FDC', 'Fédération Départementale des Chasseurs – Orne', 'FDC Orne (61)', ARRAY['61']::TEXT[]),
('federation-fdc-62', 'FDC', 'Fédération Départementale des Chasseurs – Pas-de-Calais', 'FDC Pas-de-Calais (62)', ARRAY['62']::TEXT[]),
('federation-fdc-63', 'FDC', 'Fédération Départementale des Chasseurs – Puy-de-Dôme', 'FDC Puy-de-Dôme (63)', ARRAY['63']::TEXT[]),
('federation-fdc-64', 'FDC', 'Fédération Départementale des Chasseurs – Pyrénées-Atlantiques', 'FDC Pyrénées-Atlantiques (64)', ARRAY['64']::TEXT[]),
('federation-fdc-65', 'FDC', 'Fédération Départementale des Chasseurs – Hautes-Pyrénées', 'FDC Hautes-Pyrénées (65)', ARRAY['65']::TEXT[]),
('federation-fdc-66', 'FDC', 'Fédération Départementale des Chasseurs – Pyrénées-Orientales', 'FDC Pyrénées-Orientales (66)', ARRAY['66']::TEXT[]),
('federation-fdc-67', 'FDC', 'Fédération Départementale des Chasseurs – Bas-Rhin', 'FDC Bas-Rhin (67)', ARRAY['67']::TEXT[]),
('federation-fdc-68', 'FDC', 'Fédération Départementale des Chasseurs – Haut-Rhin', 'FDC Haut-Rhin (68)', ARRAY['68']::TEXT[]),
('federation-fdc-69', 'FDC', 'Fédération Départementale des Chasseurs – Rhône', 'FDC Rhône (69)', ARRAY['69']::TEXT[]),
('federation-fdc-70', 'FDC', 'Fédération Départementale des Chasseurs – Haute-Saône', 'FDC Haute-Saône (70)', ARRAY['70']::TEXT[]),
('federation-fdc-71', 'FDC', 'Fédération Départementale des Chasseurs – Saône-et-Loire', 'FDC Saône-et-Loire (71)', ARRAY['71']::TEXT[]),
('federation-fdc-72', 'FDC', 'Fédération Départementale des Chasseurs – Sarthe', 'FDC Sarthe (72)', ARRAY['72']::TEXT[]),
('federation-fdc-73', 'FDC', 'Fédération Départementale des Chasseurs – Savoie', 'FDC Savoie (73)', ARRAY['73']::TEXT[]),
('federation-fdc-74', 'FDC', 'Fédération Départementale des Chasseurs – Haute-Savoie', 'FDC Haute-Savoie (74)', ARRAY['74']::TEXT[]),
('federation-fdc-75', 'FDC', 'Fédération Départementale des Chasseurs – Paris', 'FDC Paris (75)', ARRAY['75']::TEXT[]),
('federation-fdc-76', 'FDC', 'Fédération Départementale des Chasseurs – Seine-Maritime', 'FDC Seine-Maritime (76)', ARRAY['76']::TEXT[]),
('federation-fdc-77', 'FDC', 'Fédération Départementale des Chasseurs – Seine-et-Marne', 'FDC Seine-et-Marne (77)', ARRAY['77']::TEXT[]),
('federation-fdc-78', 'FDC', 'Fédération Départementale des Chasseurs – Yvelines', 'FDC Yvelines (78)', ARRAY['78']::TEXT[]),
('federation-fdc-79', 'FDC', 'Fédération Départementale des Chasseurs – Deux-Sèvres', 'FDC Deux-Sèvres (79)', ARRAY['79']::TEXT[]),
('federation-fdc-80', 'FDC', 'Fédération Départementale des Chasseurs – Somme', 'FDC Somme (80)', ARRAY['80']::TEXT[]),
('federation-fdc-81', 'FDC', 'Fédération Départementale des Chasseurs – Tarn', 'FDC Tarn (81)', ARRAY['81']::TEXT[]),
('federation-fdc-82', 'FDC', 'Fédération Départementale des Chasseurs – Tarn-et-Garonne', 'FDC Tarn-et-Garonne (82)', ARRAY['82']::TEXT[]),
('federation-fdc-83', 'FDC', 'Fédération Départementale des Chasseurs – Var', 'FDC Var (83)', ARRAY['83']::TEXT[]),
('federation-fdc-84', 'FDC', 'Fédération Départementale des Chasseurs – Vaucluse', 'FDC Vaucluse (84)', ARRAY['84']::TEXT[]),
('federation-fdc-85', 'FDC', 'Fédération Départementale des Chasseurs – Vendée', 'FDC Vendée (85)', ARRAY['85']::TEXT[]),
('federation-fdc-86', 'FDC', 'Fédération Départementale des Chasseurs – Vienne', 'FDC Vienne (86)', ARRAY['86']::TEXT[]),
('federation-fdc-87', 'FDC', 'Fédération Départementale des Chasseurs – Haute-Vienne', 'FDC Haute-Vienne (87)', ARRAY['87']::TEXT[]),
('federation-fdc-88', 'FDC', 'Fédération Départementale des Chasseurs – Vosges', 'FDC Vosges (88)', ARRAY['88']::TEXT[]),
('federation-fdc-89', 'FDC', 'Fédération Départementale des Chasseurs – Yonne', 'FDC Yonne (89)', ARRAY['89']::TEXT[]),
('federation-fdc-90', 'FDC', 'Fédération Départementale des Chasseurs – Territoire de Belfort', 'FDC Territoire de Belfort (90)', ARRAY['90']::TEXT[]),
('federation-fdc-91', 'FDC', 'Fédération Départementale des Chasseurs – Essonne', 'FDC Essonne (91)', ARRAY['91']::TEXT[]),
('federation-fdc-92', 'FDC', 'Fédération Départementale des Chasseurs – Hauts-de-Seine', 'FDC Hauts-de-Seine (92)', ARRAY['92']::TEXT[]),
('federation-fdc-93', 'FDC', 'Fédération Départementale des Chasseurs – Seine-Saint-Denis', 'FDC Seine-Saint-Denis (93)', ARRAY['93']::TEXT[]),
('federation-fdc-94', 'FDC', 'Fédération Départementale des Chasseurs – Val-de-Marne', 'FDC Val-de-Marne (94)', ARRAY['94']::TEXT[]),
('federation-fdc-95', 'FDC', 'Fédération Départementale des Chasseurs – Val-d''Oise', 'FDC Val-d''Oise (95)', ARRAY['95']::TEXT[]),
('federation-fdc-971', 'FDC', 'Fédération Départementale des Chasseurs – Guadeloupe', 'FDC Guadeloupe (971)', ARRAY['971']::TEXT[]),
('federation-fdc-972', 'FDC', 'Fédération Départementale des Chasseurs – Martinique', 'FDC Martinique (972)', ARRAY['972']::TEXT[]),
('federation-fdc-973', 'FDC', 'Fédération Départementale des Chasseurs – Guyane', 'FDC Guyane (973)', ARRAY['973']::TEXT[]),
('federation-fdc-974', 'FDC', 'Fédération Départementale des Chasseurs – La Réunion', 'FDC La Réunion (974)', ARRAY['974']::TEXT[]),
('federation-fdc-975', 'FDC', 'Fédération Départementale des Chasseurs – Saint-Pierre-et-Miquelon', 'FDC Saint-Pierre-et-Miquelon (975)', ARRAY['975']::TEXT[]),
('federation-fdc-976', 'FDC', 'Fédération Départementale des Chasseurs – Mayotte', 'FDC Mayotte (976)', ARRAY['976']::TEXT[]),
('federation-fdc-977', 'FDC', 'Fédération Départementale des Chasseurs – Saint-Barthélemy', 'FDC Saint-Barthélemy (977)', ARRAY['977']::TEXT[]),
('federation-fdc-978', 'FDC', 'Fédération Départementale des Chasseurs – Saint-Martin', 'FDC Saint-Martin (978)', ARRAY['978']::TEXT[]),
('federation-fdc-984', 'FDC', 'Fédération Départementale des Chasseurs – Terres australes et antarctiques françaises', 'FDC Terres australes et antarctiques françaises (984)', ARRAY['984']::TEXT[]),
('federation-fdc-986', 'FDC', 'Fédération Départementale des Chasseurs – Wallis-et-Futuna', 'FDC Wallis-et-Futuna (986)', ARRAY['986']::TEXT[]),
('federation-fdc-987', 'FDC', 'Fédération Départementale des Chasseurs – Polynésie française', 'FDC Polynésie française (987)', ARRAY['987']::TEXT[]),
('federation-fdc-988', 'FDC', 'Fédération Départementale des Chasseurs – Nouvelle-Calédonie', 'FDC Nouvelle-Calédonie (988)', ARRAY['988']::TEXT[])
ON CONFLICT ("id") DO NOTHING;
