import { CarcasseStatus, EntityRelationType, Prisma } from '@prisma/client';

export const carcasseForRegistrySelect = {
  zacharie_carcasse_id: true,
  numero_bracelet: true,
  fei_numero: true,
  type: true,
  nombre_d_animaux: true,
  heure_mise_a_mort: true,
  heure_evisceration: true,
  espece: true,
  categorie: true,
  examinateur_carcasse_sans_anomalie: false,
  examinateur_anomalies_carcasse: false,
  examinateur_anomalies_abats: false,
  examinateur_commentaire: false,
  examinateur_signed_at: false,
  intermediaire_carcasse_refus_intermediaire_id: true,
  intermediaire_carcasse_refus_motif: true,
  intermediaire_carcasse_signed_at: true,
  intermediaire_carcasse_commentaire: true,
  intermediaire_carcasse_manquante: true,
  svi_assigned_to_fei_at: true,
  svi_carcasse_manquante: true,
  svi_carcasse_consigne: true,
  svi_carcasse_consigne_at: true,
  svi_carcasse_consigne_motif: true,
  svi_carcasse_consigne_levee: true,
  svi_carcasse_consigne_levee_at: true,
  svi_carcasse_saisie: true,
  svi_carcasse_saisie_at: true,
  svi_carcasse_saisie_motif: true,
  svi_carcasse_traitement_assainissant: true,
  svi_carcasse_signed_at: true,
  svi_carcasse_commentaire: true,
  svi_carcasse_status: true,
  svi_carcasse_status_set_at: true,
  created_at: true,
  updated_at: true,
  deleted_at: true,
  is_synced: true,
  Fei: {
    select: {
      numero: true,
      date_mise_a_mort: true,
      commune_mise_a_mort: true,
      heure_mise_a_mort_premiere_carcasse: true,
      heure_evisceration_derniere_carcasse: true,
      created_by_user_id: false,
      resume_nombre_de_carcasses: true,
      examinateur_initial_offline: false,
      examinateur_initial_user_id: false,
      examinateur_initial_approbation_mise_sur_le_marche: false,
      examinateur_initial_date_approbation_mise_sur_le_marche: true,
      premier_detenteur_offline: false,
      premier_detenteur_user_id: false,
      premier_detenteur_entity_id: false,
      premier_detenteur_name_cache: true,
      premier_detenteur_date_depot_quelque_part: true,
      premier_detenteur_depot_entity_id: false,
      premier_detenteur_depot_type: false,
      svi_assigned_at: true,
      svi_entity_id: true,
      svi_user_id: true,
      svi_carcasses_saisies: true,
      svi_aucune_carcasse_saisie: true,
      svi_commentaire: true,
      svi_signed_at: true,
      svi_signed_by: true,
      fei_current_owner_user_id: false,
      fei_current_owner_user_name_cache: false,
      fei_current_owner_entity_id: false,
      fei_current_owner_entity_name_cache: false,
      fei_current_owner_role: false,
      fei_current_owner_wants_to_transfer: false,
      fei_next_owner_user_id: false,
      fei_next_owner_user_name_cache: false,
      fei_next_owner_entity_id: false,
      fei_next_owner_entity_name_cache: false,
      fei_next_owner_role: false,
      fei_prev_owner_user_id: false,
      fei_prev_owner_entity_id: false,
      fei_prev_owner_role: false,
      created_at: true,
      updated_at: true,
      deleted_at: true,
      is_synced: true,
      automatic_closed_at: true,
    },
  },
} as const;

export type CarcasseGetForRegistry = Prisma.CarcasseGetPayload<{
  select: typeof carcasseForRegistrySelect;
}>;

export type CarcasseForResponseForRegistry = CarcasseGetForRegistry & {
  svi_carcasse_status: CarcasseStatus;
  svi_carcasse_status_set_at: Date | null;
  svi_assigned_to_fei_at: Date | null;
  premier_detenteur_name_cache: string | null;
  svi_carcasse_archived: boolean | null;
};
